### ISSUE TITLE
Font Awesome in Menus

### ISSUE THREAD

**Issue by Kitsufox** [jthingelstad/foreground#164]
This isn't really so much as a bug as a feature request, but currently Font Awesome icons cannot be added to the menus. It would be amazingly useful if that became possible in the next edition.

**Comment by Hutchy68** [comment]
Removing Feature tag and making it documentation. This can be accomplished with .js easily, document how to on foreground.thingelstad.com

**Comment by Hutchy68** [comment]
Closing, documentation for PR #386 needed
