### ISSUE TITLE
Items floating over fixed topbar

### ISSUE THREAD

**Issue by CJTharp** [jthingelstad/foreground#198]
See photo. Minor, minor deal but maybe a little fix in the css. Some Items float over the top bar when it's fixed. See photo of map floating over the bar

![map floating over the fixed bar](https://cloud.githubusercontent.com/assets/9703601/5232851/b507bb22-7712-11e4-8727-d3067aca7e43.png)

**Comment by Hutchy68** [comment]
See #211 same issue, z-index. Current setting is 99, set it higher like below in MediaWiki:Foreground.css

```
.fixed {
z-index: 10000;
```
