### ISSUE TITLE
Section Horizontal Nav/Nav Bar & OpenLayers Map

### ISSUE THREAD

**Issue by CJTharp** [jthingelstad/foreground#211]
If an Openlayers map appears below a Section Horizontal Nav/Nav Bar the drop down disappears underneath the Openlayers Map. It doesn't happen with a Google Map; only with a map from OpenLayers. 

![section foreground skin with openlayers map](https://cloud.githubusercontent.com/assets/9703601/5519541/a07e3010-890e-11e4-913e-e8841c0fa4e9.png)

**Comment by Hutchy68** [comment]
All the z-indexes have long been increased. Need to determine what the Openlayers Map z-index is and adjust the navbar if fixed and the dropdowns of the menu. Specific, looking for the z-index. You can add a higher z-index in MediaWiki:Foreground.css to override the current z-index.

```
.top-bar-section .dropdown {
    z-index: 600;
}
```
