### ISSUE TITLE
Can’t use keyboard to navigate into menus

### ISSUE THREAD

**Issue by jtojnar** [jthingelstad/foreground#214]
This is huge drawback from accessibility standpoint.

**Comment by Hutchy68** [comment]
I agree and it needs to improve. Bootstrap skins are broken too. Do you have PRs to improve the accessibility?

**Comment by jtojnar** [comment]
I can make one. Should I base it on develop or foundation5 branch?

**Comment by Hutchy68** [comment]
Awesome! Foundation 5 but it might be nice to backport to the released v1.x since it has a lot of users. 

@thingles Thoughts on a release v2 using Foundation 5 by June?

**Comment by jtojnar** [comment]
#203 should probably be merged first though – there is some [merge relic](https://github.com/thingles/foreground/blob/feature/foundation5/Foreground.i18n.php#L61) that shouldn’t be there.

**Comment by Hutchy68** [comment]
Closing old issue. Someone please open a new accessibility issue with current thoughts.
