### ISSUE TITLE
Updating foreground.wikiproject.net to 2.1.0-xxx

### ISSUE THREAD

**Issue by kghbln** [jthingelstad/foreground#311]
@Hutchy68 I guess I should upgrade the wiki to 2.1.0-alpha. There we/I could test https://github.com/thingles/foreground/issues/302 but also some other CSS tweaks I have in mind and fire away the release right after. Thoughts?

**Comment by Hutchy68** [comment]
Yes, go for it. I'm prepping 2.1-beta right now

**Comment by Hutchy68** [comment]
Beta released, I still need to address these [issues](https://github.com/thingles/foreground/milestones/2.0) to clear for the 2.0 milestone. I will by Saturday have them all addressed and release Beta 2. @kghbln if you have any CSS updates, please start PR'ing them at `develop` branch and I'll merge them in. Thanks!

**Comment by kghbln** [comment]
@Hutchy68 I just updated the skin and changed the default setting to what is shown on the [features page](https://foreground.wikiproject.net/wiki/Foreground_features) I just created. This page still need some work as well as other docu pages like the one on [tabs](https://foreground.wikiproject.net/wiki/Tabs).

**Comment by Hutchy68** [comment]
Did you turn tabs on because default is set the false?

**Comment by kghbln** [comment]
> Did you turn tabs on because default is set the false?

No but is should if we would like to demo something. Still the tabs will not work here since the page is still using Foundation 4 syntax.

**Comment by Hutchy68** [comment]
Ok, the page for tabs is updated using Foundation 5 syntax.

**Comment by kghbln** [comment]
Cool, thanks a lot. I just updated the configuration page a bit. As soon as addthis is in fluff I will do final work on the page.

**Comment by kghbln** [comment]
@Hutchy68 The wiki is now at 2.1.0-rc Also switched over to use AddThis via Foreground and not via PCRGUIInserts as before.

**Comment by Hutchy68** [comment]
Awesome 😎 

I see one little thing on footer-left to fix on mobile. I’ll create an issue.

**Comment by kghbln** [comment]
You are welcome.

I have created the [Basic text elements page](https://foreground.wikiproject.net/wiki/Basic_text_elements) which is also showing some general glitches that imho should be tackled:

- Header 2 is bigger in font size that the page title
- Listing and Enumeration headers have a rather large margin to the bottom
- Headers should in general have a larger margin to the top

**Comment by Hutchy68** [comment]
>- Header 2 is bigger in font size that the page title
>- Listing and Enumeration headers have a rather large margin to the bottom
>- Enumerations have an indentation that should be much smaller
>- Listings have an indentation that is too small
>- Headers should in general have a larger margin to the top

@kghbln I addressed these issues as best as I could. MW is loading a legacy.module with CSS for elements. Real pain in the neck! Anyway, I merged in #322 so you can PULL down the changes on foreground.wikiproject.net and take a look. Here is a snip of my test installation with your source page code. `firstHeading` was just a reverse of `@media` screen size call. Fixed that too.

![image](https://user-images.githubusercontent.com/3527469/36213723-77125aec-1175-11e8-8bdc-7aa1376a4021.png)

**Comment by kghbln** [comment]
@Hutchy68 Thanks a lot. Just moved in "rc.1" and is really looks great again! :)

**Comment by kghbln** [comment]
Hmm, sublevel enumerations and listings could perhaps be tweaked a bit? However, this is a nitpick.

**Comment by Hutchy68** [comment]
>Hmm, sublevel enumerations and listings could perhaps be tweaked a bit? However, this is a nitpick.

That's going to be a hard one. 

FYI, MW is outputting a shared css module to all skins. There is an open tracker on Phabricator here: https://phabricator.wikimedia.org/T89981

This is everything being loaded automatically 😞 by all skins.

https://gist.github.com/Hutchy68/a2e6220ee471210aa522f4762df1dc06

**Comment by kghbln** [comment]
Ah, now I get it. Thanks for the insight. In fifteen years I have only seen something like this twice so we should not worries about this too much.

**Comment by Hutchy68** [comment]
Closing as not relevant any longer
