### ISSUE TITLE
VisualEditor 0.1.0 (13a585a) toolbar distorted and hidden under fixed foreground navbar

### ISSUE THREAD

**Issue by OliverO2** [jthingelstad/foreground#325]
### Setup

- Browsers and versions: Chrome 67.0.3396.99, Firefox 60.0.2
- MediaWiki version: 1.31.0
- Database version: MySQL 5.7.22-0ubuntu0.16.04.1
- PHP version: 7.0.30-0ubuntu0.16.04.1
- Foreground version: 2.1.0
- Extension version (if connected to the issue):

### Issue

At the top of the page, VisualEditor's toolbar looks distorted:
![before-top](https://user-images.githubusercontent.com/4660803/41942785-283e6372-79a1-11e8-983a-64c45139275f.jpg)

When `$wgForegroundFeatures` contains `'NavWrapperType' => 'fixed'`, VisualEditor's toolbar hides under the navbar after scrolling down:
![before-scrolled-navwrappertype-fixed](https://user-images.githubusercontent.com/4660803/41942830-5d92f858-79a1-11e8-9f3e-c698e564fa53.jpg)

**Comment by Hutchy68** [comment]
fixed PR #383
