### ISSUE TITLE
Developer Wanted! - Paid modifications for mediawiki skin foreground.

### ISSUE THREAD

**Issue by adrelanos** [jthingelstad/foreground#334]
Are you available for paid modifications for mediawiki skin foreground?

https://github.com/thingles/foreground

List of tasks:

* fix wiki Expand All / Collapse All
* mediawiki foreground skin: make items in navigation clickable without drop-down and without javascript
* There is too much white space on the left and the right side of any wiki page.
* Some of our boxes or something breaks mobile view.
* css fixes required
* mediawiki markup fix required
* CodeSelect needs fixes
* Bullet point font sizes within footnotes are too big (bigger than normal footnote size), should be smaller.
* After a bullet point, there is too little white space before the next non-bullet point text. 

task details:
https://phabricator.whonix.org/T809

If you can fix any, multiple or all of this task, please contact me.

Conditions:

- All modifications could stay Libre Software of course.
- The copyright would stay with you. I am neither interested in copyright nor attribution.
- The level of transparency is up to you.
- I am myself a huge fan of Libre Software.
- Contribute the solution as a pull request upstream whenever possible.

**Comment by jcklpe** [comment]
@adrelanos I might be able to help. At least with css type stuff. Looking at the phabricator link though it seems most of the changes have been made? Have they been merged back into the main repo, or is the newer updated branch available?

**Comment by adrelanos** [comment]
Do you have any input for https://github.com/jthingelstad/foreground/issues/182#issuecomment-435870031?

**Comment by adrelanos** [comment]
Outdated.
