### ISSUE TITLE
Bootstrap CSS link broke theme

### ISSUE THREAD

**Issue by RashkaByorn** [jthingelstad/foreground#335]
### Setup

- Browsers and versions: Google Chrome 70.0.3538.102
- MediaWiki version: 1.31.1
- Database version: 5.6.39-83.1
- PHP version: 7.0.30 (cgi-fcgi)
- Foreground version: 2.1.0

### Issue

We can not connect the link bootstrap stylesheet. Since the styles of your theme are loaded first, and after them the bootstrap is loaded, the whole theme flies and the styles are taken from the bootstrap, and not vice versa.
Tell me how i can add a bootstrap link before loading theme styles, so that the latest styles are loaded for your theme and not for bootstrap.

**Comment by Hutchy68** [comment]
Why would you load bootstrap? The skin uses Zurb Foundation as its framework.

**Comment by Hutchy68** [comment]
You can’t without causing all kinds of issues.  You’ll need to use the skin that’s based on bootstrap. You are essentially trying to make two frameworks fight each other on rendering output.

**Comment by Hutchy68** [comment]
Skin doesn't use bootstrap, closing.
