### ISSUE TITLE
Error 500 with this skin (only MW1.32 because of wfRunHooks() function)

### ISSUE THREAD

**Issue by Ash-Crow** [jthingelstad/foreground#338]
### Setup

- Browsers and versions: Firefox, latest version
- MediaWiki version: 1.32
- Database version: MySQL 5.2.24
- PHP version:7.0
- Foreground version:2.10
- Extension version (if connected to the issue):

### Issue
I just installed the skin, and when activated only the skin interface (Top bar, Actions button), but not the page contents (whatever the page is)
Looking at the console of my browser I see errors like 
`TypeError: mw.message is not a function`
`TypeError: mw.msg is not a function`

And the network tab shows a error 500 code.

The Mediawiki log files has lines like this:
`[exception] [053b8f0ba8e99bfd820297ae] /wiki/Ash:Index   Error from line 202 of /<redactedbasepath>/skins/foreground/Foreground.skin.php: Call to undefined function wfRunHooks()
`
The wiki works fine with Vector.

**Comment by Hutchy68** [comment]
There is probably some deprecated code. I’ll have to take a look.

**Comment by jamespharvey20** [comment]
All that's needed to fix is in `Foreground.skin.php`, change line 202's call to `wfRunHooks` to `Hooks::run`.  Then, it works fine.

Found this in the [MediaWiki 1.32 Release Notes](https://www.mediawiki.org/wiki/Release_notes/1.32).

I got MediaWiki logging working, but the error was being logged to apache's `error_log`.

**Comment by Hutchy68** [comment]
Thanks for the fix post @jamespharvey20 

>All that's needed to fix is in Foreground.skin.php, change line 202's call to wfRunHooks to Hooks::run. 

Repeating >

**Change line 202 in `Forground.skin.php` from `wfRunHooks` to `Hooks::run`**

I will work on releasing the fix, but I first need to test how far backwards compatibility will be. ie. Does it break MW 1.27 mainly is my focus.

**Comment by kghbln** [comment]
Since also a couple of other people noted the incompatibility on mw.org I [updated the docu](https://www.mediawiki.org/w/index.php?title=Skin:Foreground&diff=prev&oldid=3072357) pointing to this bug. I have also added a [note to <foreground.wikiproject.net>](https://foreground.wikiproject.net/w/index.php?title=Main_Page&type=revision&diff=601&oldid=535). Once the fix was release with a new version I will amend the docu accordingly.

**Comment by Extarys** [comment]
An updated version would indeed be nice. Thanks @kghbln for linking to this issue, I was going to try it :)

**Comment by MaxSem** [comment]
`Hooks::run()` was introduced in 1.22, you won't break 1.27 support.

**Comment by roguespider** [comment]
Changed line 202 in `Forground.skin.php` from `wfRunHooks` to `Hooks::run`
this does not fix anything content still missing

**Comment by patrikroy** [comment]
The fix worked perfectly for me on 1.32

**Comment by Hutchy68** [comment]
Solved with release of v2.2.0 #344

**Comment by kghbln** [comment]
@Hutchy68 FYI I finally upgraded <foreground.wikiproject.net> to MediaWiki 1.31.1 and Foreground 2.2.0 Sorry that it took me so long.
