### ISSUE TITLE
Search input alignment

### ISSUE THREAD

**Issue by hungerburg** [jthingelstad/foreground#342]
### Setup

- Browsers and versions: firefox, chrome
- MediaWiki version: 1.32
- Foreground version: latest as of now

### Issue

foundation.css adds 1rem margin to the bottom of text inputs; they then do not align with buttons placed besides, e.g. on the special:search form

PS: quite a minor issue for this appealingly slick skin :)

**Comment by Hutchy68** [comment]
I see it around line # 1447 in foundation.css file. Could do a general cleanup of foreground.css at the same time to reset the `margin: 0 0 1rem 0;` in foundation.css.

**Comment by Hutchy68** [comment]
Just pushed a fix to `develop` branch. Please test it and let me know. Thanks!

**Comment by hungerburg** [comment]
Search form is good now; Still found this http://daimon.myzel.net/Spezial:Exportieren (after quite some looking ;) (in English /Special:Export), 1rem bottom margin

**Comment by Hutchy68** [comment]
Thanks for the heads up. I found a couple other things in need of tweaking too.

**Comment by hungerburg** [comment]
Hmm, all of a sudden, the search input was up 1rem again; curious?
Line 1161 assets/stylesheets/foreground.css has a spare } right curly brace

**Comment by Hutchy68** [comment]
Oops, just fixed in `develop` branch

**Comment by hungerburg** [comment]
Everything looks fine now, closing
