### ISSUE TITLE
Mark external links

### ISSUE THREAD

**Issue by hungerburg** [jthingelstad/foreground#343]
Stock mediawiki skins provide a rule to mark links to external resources. This is missing from foreground, IMHO.

https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/skins/Vector/+/master/components/externalLinks.less

**Comment by hungerburg** [comment]
Below snippet does it in my MediaWiki:Foreground.css
```
.mw-parser-output .external {
	background: url(/skins/Vector/images/external-link-ltr-icon.png);
	background-image: url(/skins/Vector/images/external-link-ltr-icon.svg);
	background-position: center right; background-repeat: no-repeat; padding-right: 13px;
}
```

**Comment by Hutchy68** [comment]
You shouldn't use another skins images to fix another skin. We could add something about this to the https://foreground.wikiproject.net/wiki/Main_Page website. It would be a won't fix as some people do not want to mark external links as MW websites do.

**Comment by Hutchy68** [comment]
Thanks for reporting it. Closing now.
