### ISSUE TITLE
Move search from upper left to lower right in header

### ISSUE THREAD

**Issue by noloader** [jthingelstad/foreground#348]
I'm testing Foreground on MW 1.32.4 from [Crypto++ wiki](https://www.cryptopp.com/wiki/Special:Preferences). It is a very handsome skin.

I feel like the skin could be improved by moving search box from upper-left in header to lower-right in header. The skin will look more aesthetically pleasing, and reduce vertical dead space in the header.

Please see below.

![truglass](https://user-images.githubusercontent.com/3538226/66401503-3c337800-e9b1-11e9-9558-8741b0dd8c66.png)

**Comment by Hutchy68** [comment]
That's not Foreground. This is...

![image](https://user-images.githubusercontent.com/3527469/66418849-f686a780-e9d0-11e9-9aa1-10157a751251.png)

That looks like Truglass

![image](https://user-images.githubusercontent.com/3527469/66419003-47969b80-e9d1-11e9-9f74-2dd795eb78da.png)

**Comment by noloader** [comment]
Sorry about that @Hutchy68.

Foreground looks very nice, too. We added the skin also.

One small suggestion (but its not bug report worthy)... have the footer flow items horizontally, not vertically. This is what it looks like on a Desktop:

![foreground](https://user-images.githubusercontent.com/3538226/66442001-1638c280-ea07-11e9-98c5-4cb7a6120dbe.png)

And installing "Mobile View" and then clicking "Mobile View" breaks the skin. To unbreak it, click "Desktop" again.

Thanks again for a nice looking skin.
