### ISSUE TITLE
MediaWiki 1.33.1 fails to load skin due to "missing skin.json"

### ISSUE THREAD

**Issue by forkiesassds** [jthingelstad/foreground#349]
### Setup

- Browsers and versions: Chrome 77
- MediaWiki version: 1.33.1
- Database version: MariaDB 10.4
- PHP version: 7.3
- Foreground version: 2.2.1-alpha
- Extension version (if connected to the issue):

### Issue

When loading the skin using wfLoadSkin on MW 1.33.1 it fails with an error telling me that skin.json is missing. `Fatal error: Uncaught Exception: /var/www/html/skins/Foreground/skin.json does not exist! in /var/www/html/includes/registration/ExtensionRegistry.php:117 Stack trace: #0 /var/www/html/includes/GlobalFunctions.php(87): ExtensionRegistry->queue('/var/www/html/s...') #1 /var/www/html/LocalSettings.php(130): wfLoadSkin('Foreground') #2 /var/www/html/includes/Setup.php(105): require_once('/var/www/html/L...') #3 /var/www/html/includes/WebStart.php(77): require_once('/var/www/html/i...') #4 /var/www/html/index.php(39): require('/var/www/html/i...') #5 {main} thrown in /var/www/html/includes/registration/ExtensionRegistry.php on line 117`

**Comment by Hutchy68** [comment]
### The hint is in your error

Fatal error: Uncaught Exception: /var/www/html/skins/**F**oreground/skin.json does not exist!

Are you are using `wfLoadSkin( 'foreground' );` in localsettings.php and NOT `wfLoadSkin( 'Foreground' );`?

Your path to the skin is...?

```
....
  ... /skins
  ..... /foreground
  ....... /assets
  ....... /i18n
  ................
  .......  skin.json
```

**Comment by forkiesassds** [comment]
When I added the wfLoadSkin line I entered in 'Foreground' and that still gave me the error.

**Comment by forkiesassds** [comment]
Never mind. It works if I git clone but not when I download the archives.

**Comment by Hutchy68** [comment]
Because the archive changes the file structure by adding an extra top level folder
