### ISSUE TITLE
View source action don't have a icon

### ISSUE THREAD

**Issue by syhily** [jthingelstad/foreground#368]
### Setup

- Browsers and versions: The latest chrome.
- MediaWiki version: 1.34.0
- Database version: MySQL 5.7
- PHP version: 7.3
- Foreground version: Git HEAD version, https://github.com/jthingelstad/foreground/commit/c3bd0297783d78abb722069742eb87ea4175405d

### Issue

After installing this theme, the `View source` action don't have a icon. Move this line back to document ready function fixed this issue.https://github.com/jthingelstad/foreground/blob/f3ed00f9394ebe709fb525adf2bbd0aacb6ed641/assets/scripts/foreground.js#L77

**Comment by Hutchy68** [comment]
Taken care of with PR #386
