### ISSUE TITLE
caching issue: static CSS is load thorugh load.php and therefore uncacheable

### ISSUE THREAD

**Issue by adrelanos** [jthingelstad/foreground#370]
### Setup

- Browsers and versions: firefox-esr 68.8.0esr-1~deb10u1
- MediaWiki version: 1.34.1
- Database version:
- PHP version:
- Foreground version: 2.3.0

### Issue

gtmetrix.com, google pagespeed and other website speedtest / caching test websites complain that the following resources do not have a long expiration date / aren't cacheable:

* /w/load.php?lang=en&modules=ext.flaggedRevs.review&skin=foreground&version=18tly
* /w/load.php?lang=en&modules=ext.purge&skin=foreground&version=3sx9r
* /w/load.php?lang=en&modules=jquery.client&skin=foreground&version=1d1dj
* /w/load.php?lang=en&modules=jquery&skin=foreground&version=1xgm5
* /w/load.php?lang=en&modules=jquery.getAttrs&skin=foreground&version=1p30m
* /w/load.php?lang=en&modules=jquery.highlightText&skin=foreground&version=1mh8h
* /w/load.php?lang=en&modules=jquery.makeCollapsible&skin=foreground&version=rscou
* /w/load.php?lang=en&modules=jquery.suggestions&skin=foreground&version=1ucip
* /w/load.php?lang=en&modules=mediawiki.String&skin=foreground&version=1bidf
* /w/load.php?lang=en&modules=mediawiki.base&skin=foreground&version=m9box
* /w/load.php?lang=en&modules=mediawiki.cldr&skin=foreground&version=laa59
* /w/load.php?lang=en&modules=mediawiki.libs.pluralruleparser&skin=foreground&version=ckbfi
* /w/load.php?lang=en&modules=mediawiki.page.startup&skin=foreground&version=5umqm
* /w/load.php?lang=en&modules=mediawiki.Title&skin=foreground&version=sx80d
* /w/load.php?lang=en&modules=mediawiki.searchSuggest&skin=foreground&version=1ecdy
* /w/load.php?lang=en&modules=mediawiki.storage&skin=foreground&version=1dq8q
* /w/load.php?lang=en&modules=mediawiki.api&skin=foreground&version=6hk5g
* /w/load.php?lang=en&modules=site&skin=foreground&version=6dr8h
* /w/load.php?lang=en&modules=skins.foreground.modernizr&skin=foreground&version=aptx3

This is because these are fetched through `load.php`. That's probably the reason that these aren't links to `.css` or `.js` files.

These files look fairly stable.

Is this a mediawiki `load.php` issue or a foreground skin specific issue?

**Comment by JasonJAyalaP** [comment]
As far as I can tell, normal wikimedia behavior is the stylesheet line send a request to load.php like this:
```
load.php?[...]modulename.namespace.tool,tool2,tool3|differentmodule.tool,tool2
```
Which replies with a concatenated css of all thoses requested css. But somehow for whonix wiki using foreground, our html is making individual requests:
```
load.php?[...]modulename.namespace.tool
load.php?[...]modulename.namespace.tool2
load.php?[...]modulename.namespace.tool3
load.php?[...]differentmodule.tool
```

**Comment by JasonJAyalaP** [comment]
Notes:
Looking at the <script> in <head> that loads the javascript (I presume?) on whonix wiki, it's a lot different from foreground website (shown second). 

whonix wiki:
```
document.documentElement.className = "client-js";
RLCONF = {
    "wgCanonicalNamespace": "",
    "wgCanonicalSpecialPageName": !1,
    "wgNamespaceNumber": 0,
    "wgPageName": "Documentation",
    "wgTitle": "Documentation",
    "wgCurRevisionId": 58658,
    "wgRevisionId": 58658,
    "wgArticleId": 24,
    "wgIsArticle": !0,
    "wgIsRedirect": !1,
    "wgAction": "view",
    "wgUserName": "JasonJAyalaP",
    "wgUserGroups": ["Forum:Admin", "Forum:Mod", "approverevisions", "autoreview", "bureaucrat", "commentadmin", "editor", "interface-admin", "reviewer", "sysop", "translate-proofr", "uploadaccess", "widgeteditor", "*", "user", "autoconfirmed"],
    "wgCategories": [],
    "wgBreakFrames": !1,
    "wgPageContentLanguage": "en",
    "wgPageContentModel": "wikitext",
    "wgSeparatorTransformTable": ["", ""],
    "wgDigitTransformTable": ["", ""],
    "wgDefaultDateFormat": "dmy",
    "wgMonthNames": ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    "wgMonthNamesShort": ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "wgRelevantPageName": "Documentation",
    "wgRelevantArticleId": 24,
    "wgRequestId": "e6aff6dcefe407fbe7480c3a",
    "wgCSPNonce": !1,
    "wgUserId": 9,
    "wgUserEditCount": 266,
    "wgUserRegistration": 1373597825000,
    "wgUserNewMsgRevisionId": null,
    "wgIsProbablyEditable": !0,
    "wgRelevantPageIsProbablyEditable": !0,
    "wgRestrictionEdit": [],
    "wgRestrictionMove": [],
    "wgFlaggedRevsParams": {
        "tags": {
            "accuracy": {
                "levels": 3,
                "quality": 2,
                "pristine": 4
            },
            "depth": {
                "levels": 3,
                "quality": 1,
                "pristine": 4
            },
            "style": {
                "levels": 3,
                "quality": 1,
                "pristine": 4
            }
        }
    },
    "wgStableRevisionId": 58658
};
RLSTATE = {
    "site.styles": "ready",
    "noscript": "ready",
    "user.styles": "ready",
    "user": "ready",
    "user.options": "loading",
    "user.tokens": "loading",
    "ext.flaggedRevs.icons": "ready",
    "oojs-ui-core.styles": "ready",
    "oojs-ui.styles.indicators": "ready",
    "mediawiki.widgets.styles": "ready",
    "oojs-ui-core.icons": "ready",
    "mediawiki.legacy.shared": "ready",
    "mediawiki.legacy.commonPrint": "ready",
    "jquery.makeCollapsible.styles": "ready",
    "ext.flaggedRevs.basic": "ready",
    "ext.flaggedRevs.review.styles": "ready",
    "skins.foreground.styles": "ready"
};
RLPAGEMODULES = ["site", "mediawiki.page.startup", "mediawiki.page.ready", "jquery.makeCollapsible", "mediawiki.searchSuggest", "mediawiki.page.watch.ajax", "ext.flaggedRevs.advanced", "ext.flaggedRevs.review", "skins.foreground.js", "ext.purge"];

  
  (RLQ = window.RLQ || []).push(function() {
    mw.loader.implement("user.options@9lqvd", function($, jQuery, require, module) {
        /*@nomin*/
        mw.user.options.set({
            "enotifusertalkpages": "",
            "enotifwatchlistpages": "",
            "timecorrection": "Offset|0",
            "cookiewarning_dismissed": "1",
            "uls-preferences": "{\"ime\":{\"language\":\"en\",\"previousLanguages\":[\"en\"],\"previousInputMethods\":[],\"imes\":{\"en\":\"system\"}}}",
            "watchlisttoken": "a2d1b1613c5ee728979034404ac3f836a9eebb39"
        });
    });
    mw.loader.implement("user.tokens@tffin", function($, jQuery, require, module) {
        /*@nomin*/
        mw.user.tokens.set({
            "editToken": "b6a503f0ae6b1f83b5f6ef2456b23c365f1cea41+\\",
            "patrolToken": "ab25b96e602eeb171853d5e484d956715f1cea41+\\",
            "watchToken": "2c6977052dfbc7c58ba8adc7783f29e55f1cea41+\\",
            "csrfToken": "b6a503f0ae6b1f83b5f6ef2456b23c365f1cea41+\\"
        });
    });
}); 
```
Here's what a page from the foreground website looks like
```
(window.RLQ = window.RLQ || []).push(function() {
    mw.config.set({
        "wgCanonicalNamespace": "",
        "wgCanonicalSpecialPageName": false,
        "wgNamespaceNumber": 0,
        "wgPageName": "Block_Grid",
        "wgTitle": "Block Grid",
        "wgCurRevisionId": 341,
        "wgRevisionId": 341,
        "wgArticleId": 14,
        "wgIsArticle": true,
        "wgIsRedirect": false,
        "wgAction": "view",
        "wgUserName": null,
        "wgUserGroups": ["*"],
        "wgCategories": ["Documentation"],
        "wgBreakFrames": false,
        "wgPageContentLanguage": "en",
        "wgPageContentModel": "wikitext",
        "wgSeparatorTransformTable": ["", ""],
        "wgDigitTransformTable": ["", ""],
        "wgDefaultDateFormat": "dmy",
        "wgMonthNames": ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "wgMonthNamesShort": ["", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        "wgRelevantPageName": "Block_Grid",
        "wgRelevantArticleId": 14,
        "wgRequestId": "9c358a87e96a2cc9219c61c2",
        "wgIsProbablyEditable": false,
        "wgRelevantPageIsProbablyEditable": false,
        "wgRestrictionEdit": [],
        "wgRestrictionMove": [],
        "wgHeaderTabsTabIndexes": [],
        "wgVisualEditor": {
            "pageLanguageCode": "en",
            "pageLanguageDir": "ltr",
            "pageVariantFallbacks": "en",
            "usePageImages": false,
            "usePageDescriptions": false
        },
        "wgWikiEditorEnabledModules": [],
        "wgVisualEditorToolbarScrollOffset": 0,
        "wgVisualEditorUnsupportedEditParams": ["undo", "undoafter", "veswitched"],
        "wgEditSubmitButtonLabelPublish": false
    });
    mw.loader.state({
        "site.styles": "ready",
        "noscript": "ready",
        "user.styles": "ready",
        "user": "ready",
        "site": "ready",
        "user.options": "ready",
        "user.tokens": "loading",
        "ext.CookieWarning.styles": "ready",
        "ext.visualEditor.desktopArticleTarget.noscript": "ready",
        "mediawiki.legacy.shared": "ready",
        "mediawiki.legacy.commonPrint": "ready",
        "mediawiki.sectionAnchor": "ready",
        "skins.foreground.styles": "ready"
    });
    mw.loader.implement("user.tokens@0be4p61", function($, jQuery, require, module) {
        /*@nomin*/
        mw.user.tokens.set({
            "editToken": "+\\",
            "patrolToken": "+\\",
            "watchToken": "+\\",
            "csrfToken": "+\\"
        });
    });
    mw.loader.load(["mediawiki.page.startup", "mediawiki.user", "mediawiki.hidpi", "mediawiki.page.ready", "mediawiki.searchSuggest", "ext.CookieWarning", "ext.headertabs", "ext.headertabs.large", "ext.visualEditor.desktopArticleTarget.init", "ext.visualEditor.targetLoader", "skins.foreground.js"]);
});
```

**Comment by Hutchy68** [comment]
See https://www.mediawiki.org/wiki/ResourceLoader

**Comment by adrelanos** [comment]
I am aware of this page, but can this issue be fixed?

**Comment by Hutchy68** [comment]
Sounds like you had ResourceModules debug set to true. Also there is a method to set caches of the versions of modules. I think you solved your issue a while ago?? Just checked your gtmetrix...

![image](https://user-images.githubusercontent.com/3527469/102259376-0525f400-3edd-11eb-9ba3-0310b2a1f59f.png)

**Comment by adrelanos** [comment]
> Sounds like you had ResourceModules debug set to true.

I was looking how to even enable ResourceModules debug mode.

https://www.mediawiki.org/wiki/ResourceLoader/Architecture#Debug_mode

I never enabled it.

> Also there is a method to set caches of the versions of modules.

Please elaborate.

> I think you solved your issue a while ago?? Just checked your gtmetrix...
> 
> ![image](https://user-images.githubusercontent.com/3527469/102259376-0525f400-3edd-11eb-9ba3-0310b2a1f59f.png)

Just a workaround on the server level. Not fixed on webapp level.

**Comment by Hutchy68** [comment]
This is not a skin issue. I can see how everyone might think it is because `skin=foreground`. This is the method of designation for each specific skin. If someone was offering 5 skins on a website, you would see each of those skins with their own specific `skin=a name`. 

I'm sorry, but debug mode had to be enabled. I can replicate your output with ?debug=true at the end of the url. Without debug=true everything I see looks normal and correct now. Although, I see you are adding `.css` to the end of the file name. ? `.htaccess` rewrite? Plus the url is slightly altered with `==` the predominate differences.

Debug ON
![image](https://user-images.githubusercontent.com/3527469/102622248-beb7db80-410e-11eb-86e4-217ec9e1353c.png)

Without Debug
![image](https://user-images.githubusercontent.com/3527469/102622525-2b32da80-410f-11eb-9dec-706040a03e18.png)

`$wgResourceLoaderDebug = true;` did someone drop it in a odd place? In a skin file? Not apparent in LocalSettings. Another extension trying to debug something? It is a global.

https://www.mediawiki.org/wiki/Manual:$wgResourceLoaderMaxage
