### ISSUE TITLE
[BUG] Duplicated ID

### ISSUE THREAD

**Issue by Rififia** [jthingelstad/foreground#371]
### Setup

- Browsers and versions: Firefox 79.0
- MediaWiki version: 1.31.1
- Database version: MySQL  5.6.45-log
- PHP version: 7.2.33
- Foreground version: 2.2.0

### Issue
There is a duplicated ID in Foreground.skin.php at lines 251-252 : footer-id.
I'm trying to see how to change it without destroying the style.

**Comment by Hutchy68** [comment]
Merged in, closing.
