### ISSUE TITLE
My icons do not show or look broken in the sidebar and/or drop down menu. What is wrong?

### ISSUE THREAD

**Issue by Ismacomerlato** [jthingelstad/foreground#379]
Hello, i'm using MW version 1.34.1 and Foreground 2.3.0 and the small icons are appearing as small square boxes, not showing the small images on the dropdown menus. What is wrong?

**Comment by Hutchy68** [comment]
That's a server issue. I have a patch for a work around, but in another skin. I don't think it ever made it into Foreground. Please see. https://pivot.wikiproject.net/wiki/FAQs (My icons are broken).
