### ISSUE TITLE
Hidden categories shown unconditionally

### ISSUE THREAD

**Issue by kghbln** [jthingelstad/foreground#388]
### Setup

- Browsers and versions: Fx 84
- MediaWiki version: 1.31.12 (196beec)
- Database version: 10.3.27-MariaDB-0+deb10u1
- PHP version: 7.3.19-1~deb10u1 (apache2handler)
- Foreground version: 2.2.0 (1cdda4d) 20:44, 8 March 2019
- Extension version (if connected to the issue):

### Issue

Even if I do not tick "Show hidden cats" in "Appearance" --> "Advanced options" on special page "Preferences" I can see the categories containing the `__HIDDENCAT__` behaviour switch. Same goes if I am not logged in.

### Example
See category "Test pages" on [Test Page](https://foreground.wikiproject.net/wiki/Test_Page) which uses the behaviour switch.

**Comment by Hutchy68** [comment]
Odd, I don't see any categories on this page.

![image](https://user-images.githubusercontent.com/3527469/107688268-741d9000-6c75-11eb-8180-8aba642497ff.png)

**Comment by Hutchy68** [comment]
One my test wiki of 1.35 Test 1 category is hidden and is hidden. Test and Test 2 not hidden.

![image](https://user-images.githubusercontent.com/3527469/107688546-c3fc5700-6c75-11eb-832e-5193612b9d6d.png)

**Comment by kghbln** [comment]
@Hutchy68 Indeed, this is really odd. Currently I cannot see this either. It must be a caching issue. I opened this since I saw this not just on the demo wiki. Anyhow, let's close it for now. In case I observe something again I could come back here.

Thanks for looking at this!
